version: "2"

services:
  kafka:
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      ADVERTISED_PORT: 9092
      ADVERTISED_HOST: localhost
      KAFKA_CREATE_TOPICS: "accounts:1:1"
